// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// AchievementService is an autogenerated mock type for the AchievementService type
type AchievementService struct {
	mock.Mock
}

// CreateAchievement provides a mock function with given fields: ctx, cDetail, ID
func (_m *AchievementService) CreateAchievement(ctx context.Context, cDetail dto.CreateAchievementRequest, ID string) (int, error) {
	ret := _m.Called(ctx, cDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest, string) (int, error)); ok {
		return rf(ctx, cDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest, string) int); ok {
		r0 = rf(ctx, cDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateAchievementRequest, string) error); ok {
		r1 = rf(ctx, cDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAchievement provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *AchievementService) UpdateAchievement(ctx context.Context, profileID string, eduID string, req dto.UpdateAchievementRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateAchievementRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateAchievementRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateAchievementRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAchievementService creates a new instance of AchievementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAchievementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AchievementService {
	mock := &AchievementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
