// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// AchievementService is an autogenerated mock type for the AchievementService type
type AchievementService struct {
	mock.Mock
}

// CreateAchievement provides a mock function with given fields: ctx, cDetail
func (_m *AchievementService) CreateAchievement(ctx context.Context, cDetail dto.CreateAchievementRequest) (int, error) {
	ret := _m.Called(ctx, cDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest) (int, error)); ok {
		return rf(ctx, cDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest) int); ok {
		r0 = rf(ctx, cDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateAchievementRequest) error); ok {
		r1 = rf(ctx, cDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAchievementService creates a new instance of AchievementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAchievementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AchievementService {
	mock := &AchievementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
