// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	specs "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/specs"
)

// CertificateService is an autogenerated mock type for the CertificateService type
type CertificateService struct {
	mock.Mock
}

// CreateCertificate provides a mock function with given fields: ctx, cDetail, profileID, userID
func (_m *CertificateService) CreateCertificate(ctx context.Context, cDetail specs.CreateCertificateRequest, profileID int, userID int) (int, error) {
	ret := _m.Called(ctx, cDetail, profileID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, specs.CreateCertificateRequest, int, int) (int, error)); ok {
		return rf(ctx, cDetail, profileID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, specs.CreateCertificateRequest, int, int) int); ok {
		r0 = rf(ctx, cDetail, profileID, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, specs.CreateCertificateRequest, int, int) error); ok {
		r1 = rf(ctx, cDetail, profileID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCertificate provides a mock function with given fields: ctx, profileID, certitificateID
func (_m *CertificateService) DeleteCertificate(ctx context.Context, profileID int, certitificateID int) error {
	ret := _m.Called(ctx, profileID, certitificateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, profileID, certitificateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCertificates provides a mock function with given fields: ctx, profileID, fitler
func (_m *CertificateService) ListCertificates(ctx context.Context, profileID int, fitler specs.ListCertificateFilter) ([]specs.CertificateResponse, error) {
	ret := _m.Called(ctx, profileID, fitler)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []specs.CertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListCertificateFilter) ([]specs.CertificateResponse, error)); ok {
		return rf(ctx, profileID, fitler)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListCertificateFilter) []specs.CertificateResponse); ok {
		r0 = rf(ctx, profileID, fitler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]specs.CertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, specs.ListCertificateFilter) error); ok {
		r1 = rf(ctx, profileID, fitler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCertificate provides a mock function with given fields: ctx, profileID, certID, userID, req
func (_m *CertificateService) UpdateCertificate(ctx context.Context, profileID int, certID int, userID int, req specs.UpdateCertificateRequest) (int, error) {
	ret := _m.Called(ctx, profileID, certID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, specs.UpdateCertificateRequest) (int, error)); ok {
		return rf(ctx, profileID, certID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, specs.UpdateCertificateRequest) int); ok {
		r0 = rf(ctx, profileID, certID, userID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, specs.UpdateCertificateRequest) error); ok {
		r1 = rf(ctx, profileID, certID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateService creates a new instance of CertificateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateService {
	mock := &CertificateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
