// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// CertificateService is an autogenerated mock type for the CertificateService type
type CertificateService struct {
	mock.Mock
}

// CreateCertificate provides a mock function with given fields: ctx, cDetail, ID
func (_m *CertificateService) CreateCertificate(ctx context.Context, cDetail dto.CreateCertificateRequest, ID string) (int, error) {
	ret := _m.Called(ctx, cDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest, string) (int, error)); ok {
		return rf(ctx, cDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest, string) int); ok {
		r0 = rf(ctx, cDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCertificateRequest, string) error); ok {
		r1 = rf(ctx, cDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCertificate provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *CertificateService) UpdateCertificate(ctx context.Context, profileID string, eduID string, req dto.UpdateCertificateRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateCertificateRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateCertificateRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateCertificateRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateService creates a new instance of CertificateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateService {
	mock := &CertificateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
