// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	specs "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/specs"
)

// EducationService is an autogenerated mock type for the EducationService type
type EducationService struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, eduDetail, profileID, userID
func (_m *EducationService) CreateEducation(ctx context.Context, eduDetail specs.CreateEducationRequest, profileID int, userID int) (int, error) {
	ret := _m.Called(ctx, eduDetail, profileID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, specs.CreateEducationRequest, int, int) (int, error)); ok {
		return rf(ctx, eduDetail, profileID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, specs.CreateEducationRequest, int, int) int); ok {
		r0 = rf(ctx, eduDetail, profileID, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, specs.CreateEducationRequest, int, int) error); ok {
		r1 = rf(ctx, eduDetail, profileID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEducation provides a mock function with given fields: ctx, req
func (_m *EducationService) DeleteEducation(ctx context.Context, req specs.DeleteEducationRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, specs.DeleteEducationRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListEducations provides a mock function with given fields: ctx, id, filter
func (_m *EducationService) ListEducations(ctx context.Context, id int, filter specs.ListEducationsFilter) ([]specs.EducationResponse, error) {
	ret := _m.Called(ctx, id, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListEducations")
	}

	var r0 []specs.EducationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListEducationsFilter) ([]specs.EducationResponse, error)); ok {
		return rf(ctx, id, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListEducationsFilter) []specs.EducationResponse); ok {
		r0 = rf(ctx, id, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]specs.EducationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, specs.ListEducationsFilter) error); ok {
		r1 = rf(ctx, id, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEducation provides a mock function with given fields: ctx, profileID, eduID, userID, req
func (_m *EducationService) UpdateEducation(ctx context.Context, profileID int, eduID int, userID int, req specs.UpdateEducationRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, specs.UpdateEducationRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, specs.UpdateEducationRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, userID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, specs.UpdateEducationRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEducationService creates a new instance of EducationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEducationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EducationService {
	mock := &EducationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
