// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// ExperienceService is an autogenerated mock type for the ExperienceService type
type ExperienceService struct {
	mock.Mock
}

// CreateExperience provides a mock function with given fields: ctx, expDetail
func (_m *ExperienceService) CreateExperience(ctx context.Context, expDetail dto.CreateExperienceRequest) (int, error) {
	ret := _m.Called(ctx, expDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateExperience")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest) (int, error)); ok {
		return rf(ctx, expDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest) int); ok {
		r0 = rf(ctx, expDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateExperienceRequest) error); ok {
		r1 = rf(ctx, expDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExperienceService creates a new instance of ExperienceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExperienceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExperienceService {
	mock := &ExperienceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
