// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateAchievement provides a mock function with given fields: ctx, cDetail
func (_m *Service) CreateAchievement(ctx context.Context, cDetail dto.CreateAchievementRequest) (int, error) {
	ret := _m.Called(ctx, cDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest) (int, error)); ok {
		return rf(ctx, cDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest) int); ok {
		r0 = rf(ctx, cDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateAchievementRequest) error); ok {
		r1 = rf(ctx, cDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCertificate provides a mock function with given fields: ctx, cDetail
func (_m *Service) CreateCertificate(ctx context.Context, cDetail dto.CreateCertificateRequest) (int, error) {
	ret := _m.Called(ctx, cDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest) (int, error)); ok {
		return rf(ctx, cDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest) int); ok {
		r0 = rf(ctx, cDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCertificateRequest) error); ok {
		r1 = rf(ctx, cDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEducation provides a mock function with given fields: ctx, eduDetail
func (_m *Service) CreateEducation(ctx context.Context, eduDetail dto.CreateEducationRequest) (int, error) {
	ret := _m.Called(ctx, eduDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateEducationRequest) (int, error)); ok {
		return rf(ctx, eduDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateEducationRequest) int); ok {
		r0 = rf(ctx, eduDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateEducationRequest) error); ok {
		r1 = rf(ctx, eduDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExperience provides a mock function with given fields: ctx, expDetail
func (_m *Service) CreateExperience(ctx context.Context, expDetail dto.CreateExperienceRequest) (int, error) {
	ret := _m.Called(ctx, expDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateExperience")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest) (int, error)); ok {
		return rf(ctx, expDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest) int); ok {
		r0 = rf(ctx, expDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateExperienceRequest) error); ok {
		r1 = rf(ctx, expDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProfile provides a mock function with given fields: ctx, profileDetail
func (_m *Service) CreateProfile(ctx context.Context, profileDetail dto.CreateProfileRequest) (int, error) {
	ret := _m.Called(ctx, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) (int, error)); ok {
		return rf(ctx, profileDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) int); ok {
		r0 = rf(ctx, profileDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateProfileRequest) error); ok {
		r1 = rf(ctx, profileDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProject provides a mock function with given fields: ctx, projDetail
func (_m *Service) CreateProject(ctx context.Context, projDetail dto.CreateProjectRequest) (int, error) {
	ret := _m.Called(ctx, projDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProjectRequest) (int, error)); ok {
		return rf(ctx, projDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProjectRequest) int); ok {
		r0 = rf(ctx, projDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateProjectRequest) error); ok {
		r1 = rf(ctx, projDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateLoginToken provides a mock function with given fields: ctx, email
func (_m *Service) GenerateLoginToken(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateLoginToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEducation provides a mock function with given fields: ctx, profileID
func (_m *Service) GetEducation(ctx context.Context, profileID string) ([]dto.EducationResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetEducation")
	}

	var r0 []dto.EducationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.EducationResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.EducationResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.EducationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExperience provides a mock function with given fields: ctx, profileID
func (_m *Service) GetExperience(ctx context.Context, profileID string) ([]dto.ExperienceResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetExperience")
	}

	var r0 []dto.ExperienceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.ExperienceResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.ExperienceResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ExperienceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, profileID
func (_m *Service) GetProfile(ctx context.Context, profileID string) (dto.ResponseProfile, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 dto.ResponseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.ResponseProfile, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.ResponseProfile); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(dto.ResponseProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProject provides a mock function with given fields: ctx, profileID
func (_m *Service) GetProject(ctx context.Context, profileID string) ([]dto.ProjectResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 []dto.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.ProjectResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.ProjectResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAchievements provides a mock function with given fields: ctx, profileID
func (_m *Service) ListAchievements(ctx context.Context, profileID int) ([]dto.AchievementResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for ListAchievements")
	}

	var r0 []dto.AchievementResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]dto.AchievementResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []dto.AchievementResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AchievementResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCertificates provides a mock function with given fields: ctx, profileID
func (_m *Service) ListCertificates(ctx context.Context, profileID int) ([]dto.CertificateResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []dto.CertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]dto.CertificateResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []dto.CertificateResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProfiles provides a mock function with given fields: ctx
func (_m *Service) ListProfiles(ctx context.Context) ([]dto.ListProfiles, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 []dto.ListProfiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.ListProfiles, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.ListProfiles); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListProfiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEducation provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateEducation(ctx context.Context, profileID string, eduID string, req dto.UpdateEducationRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateEducationRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateEducationRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateEducationRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, profileID, profileDetail
func (_m *Service) UpdateProfile(ctx context.Context, profileID string, profileDetail dto.UpdateProfileRequest) (int, error) {
	ret := _m.Called(ctx, profileID, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateProfileRequest) (int, error)); ok {
		return rf(ctx, profileID, profileDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateProfileRequest) int); ok {
		r0 = rf(ctx, profileID, profileDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, profileID, profileDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
