// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateAchievement provides a mock function with given fields: ctx, cDetail, ID
func (_m *Service) CreateAchievement(ctx context.Context, cDetail dto.CreateAchievementRequest, ID string) (int, error) {
	ret := _m.Called(ctx, cDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest, string) (int, error)); ok {
		return rf(ctx, cDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateAchievementRequest, string) int); ok {
		r0 = rf(ctx, cDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateAchievementRequest, string) error); ok {
		r1 = rf(ctx, cDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCertificate provides a mock function with given fields: ctx, cDetail, ID
func (_m *Service) CreateCertificate(ctx context.Context, cDetail dto.CreateCertificateRequest, ID string) (int, error) {
	ret := _m.Called(ctx, cDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest, string) (int, error)); ok {
		return rf(ctx, cDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCertificateRequest, string) int); ok {
		r0 = rf(ctx, cDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCertificateRequest, string) error); ok {
		r1 = rf(ctx, cDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEducation provides a mock function with given fields: ctx, eduDetail, ID
func (_m *Service) CreateEducation(ctx context.Context, eduDetail dto.CreateEducationRequest, ID string) (int, error) {
	ret := _m.Called(ctx, eduDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateEducationRequest, string) (int, error)); ok {
		return rf(ctx, eduDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateEducationRequest, string) int); ok {
		r0 = rf(ctx, eduDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateEducationRequest, string) error); ok {
		r1 = rf(ctx, eduDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExperience provides a mock function with given fields: ctx, expDetail, ID
func (_m *Service) CreateExperience(ctx context.Context, expDetail dto.CreateExperienceRequest, ID string) (int, error) {
	ret := _m.Called(ctx, expDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateExperience")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest, string) (int, error)); ok {
		return rf(ctx, expDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateExperienceRequest, string) int); ok {
		r0 = rf(ctx, expDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateExperienceRequest, string) error); ok {
		r1 = rf(ctx, expDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProfile provides a mock function with given fields: ctx, profileDetail
func (_m *Service) CreateProfile(ctx context.Context, profileDetail dto.CreateProfileRequest) (int, error) {
	ret := _m.Called(ctx, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) (int, error)); ok {
		return rf(ctx, profileDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) int); ok {
		r0 = rf(ctx, profileDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateProfileRequest) error); ok {
		r1 = rf(ctx, profileDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProject provides a mock function with given fields: ctx, projDetail, ID
func (_m *Service) CreateProject(ctx context.Context, projDetail dto.CreateProjectRequest, ID string) (int, error) {
	ret := _m.Called(ctx, projDetail, ID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProjectRequest, string) (int, error)); ok {
		return rf(ctx, projDetail, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProjectRequest, string) int); ok {
		r0 = rf(ctx, projDetail, ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateProjectRequest, string) error); ok {
		r1 = rf(ctx, projDetail, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEducation provides a mock function with given fields: ctx, profileID
func (_m *Service) GetEducation(ctx context.Context, profileID string) ([]dto.EducationResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetEducation")
	}

	var r0 []dto.EducationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.EducationResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.EducationResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.EducationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExperience provides a mock function with given fields: ctx, profileID
func (_m *Service) GetExperience(ctx context.Context, profileID string) ([]dto.ExperienceResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetExperience")
	}

	var r0 []dto.ExperienceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.ExperienceResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.ExperienceResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ExperienceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, profileID
func (_m *Service) GetProfile(ctx context.Context, profileID string) (dto.ResponseProfile, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 dto.ResponseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.ResponseProfile, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.ResponseProfile); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(dto.ResponseProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProject provides a mock function with given fields: ctx, profileID
func (_m *Service) GetProject(ctx context.Context, profileID string) ([]dto.ProjectResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 []dto.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.ProjectResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.ProjectResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProfiles provides a mock function with given fields: ctx
func (_m *Service) ListProfiles(ctx context.Context) ([]dto.ListProfiles, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 []dto.ListProfiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.ListProfiles, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.ListProfiles); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListProfiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSkills provides a mock function with given fields: ctx
func (_m *Service) ListSkills(ctx context.Context) (dto.ListSkills, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSkills")
	}

	var r0 dto.ListSkills
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dto.ListSkills, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dto.ListSkills); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dto.ListSkills)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAchievement provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateAchievement(ctx context.Context, profileID string, eduID string, req dto.UpdateAchievementRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAchievement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateAchievementRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateAchievementRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateAchievementRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCertificate provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateCertificate(ctx context.Context, profileID string, eduID string, req dto.UpdateCertificateRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateCertificateRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateCertificateRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateCertificateRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEducation provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateEducation(ctx context.Context, profileID string, eduID string, req dto.UpdateEducationRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateEducationRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateEducationRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateEducationRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateExperience provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateExperience(ctx context.Context, profileID string, eduID string, req dto.UpdateExperienceRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExperience")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateExperienceRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateExperienceRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateExperienceRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, profileID, profileDetail
func (_m *Service) UpdateProfile(ctx context.Context, profileID string, profileDetail dto.UpdateProfileRequest) (int, error) {
	ret := _m.Called(ctx, profileID, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateProfileRequest) (int, error)); ok {
		return rf(ctx, profileID, profileDetail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateProfileRequest) int); ok {
		r0 = rf(ctx, profileID, profileDetail)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, profileID, profileDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProject provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *Service) UpdateProject(ctx context.Context, profileID string, eduID string, req dto.UpdateProjectRequest) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateProjectRequest) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, dto.UpdateProjectRequest) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, dto.UpdateProjectRequest) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
