services:
  # react_app:
  #   build: 
  #     context: ../profile_builder_frontend
  #     dockerfile: ../profile_builder_frontend/Dockerfile.dev
  #   container_name: react_app
  #   ports:
  #     - "3000:3000"

  profile_builder_go:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: profile_builder_go
    ports:
      - "3001:3001"
    # depends_on:
    #   profile_builder_db:
    #     condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  # profile_builder_db:
  #   container_name: profile_builder_db
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=profile_builder
  #   ports:
  #     - "5432:5432" 
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - ./internal/db/migrations:/docker-entrypoint-initdb.d/migr
  #     - pgData:/var/lib/postgresql/data

volumes:
  pgData: {}