openapi: 3.0.3
info:
  title: Profile Builder API
  description: API documentation for Creating a Profile Builder Application with Admin Control and some advanced features.
    
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/profiles:
    get:
      summary: List of Profiles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Profile
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profile:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    gender:
                      type: string
                    mobile:
                      type: string
                    designation:
                      type: string
                    description:
                      type: string
                    title:
                      type: string
                    years_of_experience:
                      type: integer
                    primary_skills:
                      type: array
                      items:
                        type: string
                    secondary_skills:
                      type: array
                      items:
                        type: string
                    github_link:
                      type: string
                    linkedin_link:
                      type: string
                    career_objectives:
                      type: string
      responses:
        '201':
          description: Profile created

  /api/skills:
    get:
      summary: List of Skills
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response

  /api/profiles/{profileId}:
    get:
      summary: Get Profile by ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response

  /api/profiles/{profileId}/educations:
    get:
      summary: Get Educations by Profile ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Educations
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                educations:
                  type: array
                  items:
                    type: object
                    properties:
                      degree:
                        type: string
                      university_name:
                        type: string
                      place:
                        type: string
                      percent_or_cgpa:
                        type: string
                      passing_year:
                        type: string
      responses:
        '201':
          description: Education created

  /api/profiles/{profileId}/projects:
    get:
      summary: Get Projects by Profile ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Projects
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                projects:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      role:
                        type: string
                      responsibilities:
                        type: string
                      technologies:
                        type: array
                        items:
                          type: string
                      tech_worked_on:
                        type: array
                        items:
                          type: string
                      working_start_date:
                        type: string
                      working_end_date:
                        type: string
                      duration:
                        type: string
      responses:
        '201':
          description: Project created

  /api/profiles/{profileId}/experiences:
    get:
      summary: Get Experiences by Profile ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Experiences
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                experiences:
                  type: array
                  items:
                    type: object
                    properties:
                      designation:
                        type: string
                      company_name:
                        type: string
                      from_date:
                        type: string
                      to_date:
                        type: string
      responses:
        '201':
          description: Experience created

  /api/profiles/{profileId}/achievements:
    get:
      summary: Get Achievements by Profile ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Achievements
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                achievements:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
      responses:
        '201':
          description: Achievement created

  /api/profiles/{profileId}/certificates:
    get:
      summary: Get Certificates by Profile ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Certificates
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                certificates:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      organization_name:
                        type: string
                      description:
                        type: string
                      issued_date:
                        type: string
                      from_date:
                        type: string
                      to_date:
                        type: string
      responses:
        '201':
          description: Certificate created

  /login:
    post:
      summary: User Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Successful login

  /api/profiles/{profileId}/educations/{educationId}:
    put:
      summary: Update Education of Specific ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
        - name: educationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                education:
                  type: object
                  properties:
                    degree:
                      type: string
                    university_name:
                      type: string
                    place:
                      type: string
                    percent_or_cgpa:
                      type: string
                    passing_year:
                      type: string
      responses:
        '200':
          description: Education updated

  /api/profiles/{profileId}/experiences/{experienceId}:
    put:
      summary: Update Experience of Specific ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
        - name: experienceId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                experience:
                  type: object
                  properties:
                    designation:
                      type: string
                    company_name:
                      type: string
                    from_date:
                      type: string
                    to_date:
                      type: string
      responses:
        '200':
          description: Experience updated

  /api/profiles/{profileId}/projects/{projectId}:
    put:
      summary: Update Project of Specific ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    role:
                      type: string
                    responsibilities:
                      type: string
                    technologies:
                      type: array
                      items:
                        type: string
                    tech_worked_on:
                      type: array
                      items:
                        type: string
                    working_start_date:
                      type: string
                    working_end_date:
                      type: string
                    duration:
                      type: string
      responses:
        '200':
          description: Project updated

  /api/profiles/{profileId}/certificates/{certificateId}:
    put:
      summary: Update Certificate of Specific ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
        - name: certificateId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                certificate:
                  type: object
                  properties:
                    name:
                      type: string
                    organization_name:
                      type: string
                    description:
                      type: string
                    issued_date:
                      type: string
                    from_date:
                      type: string
                    to_date:
                      type: string
      responses:
        '200':
          description: Certificate updated

  /api/profiles/{profileId}/achievements/{achievementId}:
    put:
      summary: Update Achievement of Specific ID
      security:
        - bearerAuth: []
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
        - name: achievementId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                achievement:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
      responses:
        '200':
          description: Achievement updated
