// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// AchievementStorer is an autogenerated mock type for the AchievementStorer type
type AchievementStorer struct {
	mock.Mock
}

// CreateAchievement provides a mock function with given fields: ctx, values
func (_m *AchievementStorer) CreateAchievement(ctx context.Context, values []repository.AchievementDao) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateAchievement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.AchievementDao) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAchievementStorer creates a new instance of AchievementStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAchievementStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AchievementStorer {
	mock := &AchievementStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
