// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"

	specs "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/specs"
)

// CertificateStorer is an autogenerated mock type for the CertificateStorer type
type CertificateStorer struct {
	mock.Mock
}

// CreateCertificate provides a mock function with given fields: ctx, values, tx
func (_m *CertificateStorer) CreateCertificate(ctx context.Context, values []repository.CertificateRepo, tx pgx.Tx) error {
	ret := _m.Called(ctx, values, tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.CertificateRepo, pgx.Tx) error); ok {
		r0 = rf(ctx, values, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCertificate provides a mock function with given fields: ctx, profileID, certificateID, tx
func (_m *CertificateStorer) DeleteCertificate(ctx context.Context, profileID int, certificateID int, tx pgx.Tx) error {
	ret := _m.Called(ctx, profileID, certificateID, tx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, pgx.Tx) error); ok {
		r0 = rf(ctx, profileID, certificateID, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCertificates provides a mock function with given fields: ctx, profileID, filter, tx
func (_m *CertificateStorer) ListCertificates(ctx context.Context, profileID int, filter specs.ListCertificateFilter, tx pgx.Tx) ([]specs.CertificateResponse, error) {
	ret := _m.Called(ctx, profileID, filter, tx)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []specs.CertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListCertificateFilter, pgx.Tx) ([]specs.CertificateResponse, error)); ok {
		return rf(ctx, profileID, filter, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, specs.ListCertificateFilter, pgx.Tx) []specs.CertificateResponse); ok {
		r0 = rf(ctx, profileID, filter, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]specs.CertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, specs.ListCertificateFilter, pgx.Tx) error); ok {
		r1 = rf(ctx, profileID, filter, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCertificate provides a mock function with given fields: ctx, profileID, eduID, req, tx
func (_m *CertificateStorer) UpdateCertificate(ctx context.Context, profileID int, eduID int, req repository.UpdateCertificateRepo, tx pgx.Tx) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.UpdateCertificateRepo, pgx.Tx) (int, error)); ok {
		return rf(ctx, profileID, eduID, req, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.UpdateCertificateRepo, pgx.Tx) int); ok {
		r0 = rf(ctx, profileID, eduID, req, tx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, repository.UpdateCertificateRepo, pgx.Tx) error); ok {
		r1 = rf(ctx, profileID, eduID, req, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateStorer creates a new instance of CertificateStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateStorer {
	mock := &CertificateStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
