// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"
)

// CertificateStorer is an autogenerated mock type for the CertificateStorer type
type CertificateStorer struct {
	mock.Mock
}

// CreateCertificate provides a mock function with given fields: ctx, values
func (_m *CertificateStorer) CreateCertificate(ctx context.Context, values []repository.CertificateDao) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.CertificateDao) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCertificates provides a mock function with given fields: ctx, profileID
func (_m *CertificateStorer) ListCertificates(ctx context.Context, profileID int) ([]dto.CertificateResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []dto.CertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]dto.CertificateResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []dto.CertificateResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateStorer creates a new instance of CertificateStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateStorer {
	mock := &CertificateStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
