// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// EducationStorer is an autogenerated mock type for the EducationStorer type
type EducationStorer struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, values
func (_m *EducationStorer) CreateEducation(ctx context.Context, values []repository.EducationDao) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.EducationDao) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEducationStorer creates a new instance of EducationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEducationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EducationStorer {
	mock := &EducationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
