// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	specs "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/specs"
	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// EducationStorer is an autogenerated mock type for the EducationStorer type
type EducationStorer struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, values
func (_m *EducationStorer) CreateEducation(ctx context.Context, values []repository.EducationRepo) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.EducationRepo) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEducation provides a mock function with given fields: ctx, profileID
func (_m *EducationStorer) GetEducation(ctx context.Context, profileID int) ([]specs.EducationResponse, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetEducation")
	}

	var r0 []specs.EducationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]specs.EducationResponse, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []specs.EducationResponse); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]specs.EducationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEducation provides a mock function with given fields: ctx, profileID, eduID, req
func (_m *EducationStorer) UpdateEducation(ctx context.Context, profileID int, eduID int, req repository.UpdateEducationRepo) (int, error) {
	ret := _m.Called(ctx, profileID, eduID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEducation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.UpdateEducationRepo) (int, error)); ok {
		return rf(ctx, profileID, eduID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, repository.UpdateEducationRepo) int); ok {
		r0 = rf(ctx, profileID, eduID, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, repository.UpdateEducationRepo) error); ok {
		r1 = rf(ctx, profileID, eduID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEducationStorer creates a new instance of EducationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEducationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EducationStorer {
	mock := &EducationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
