// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"

	specs "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/specs"
)

// EmailStorer is an autogenerated mock type for the EmailStorer type
type EmailStorer struct {
	mock.Mock
}

// CreateInvitation provides a mock function with given fields: ctx, invitation, tx
func (_m *EmailStorer) CreateInvitation(ctx context.Context, invitation repository.Invitations, tx pgx.Tx) error {
	ret := _m.Called(ctx, invitation, tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Invitations, pgx.Tx) error); ok {
		r0 = rf(ctx, invitation, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInvitations provides a mock function with given fields: ctx, getRequest, tx
func (_m *EmailStorer) GetInvitations(ctx context.Context, getRequest repository.GetRequest, tx pgx.Tx) (specs.InvitationResponse, error) {
	ret := _m.Called(ctx, getRequest, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitations")
	}

	var r0 specs.InvitationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetRequest, pgx.Tx) (specs.InvitationResponse, error)); ok {
		return rf(ctx, getRequest, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetRequest, pgx.Tx) specs.InvitationResponse); ok {
		r0 = rf(ctx, getRequest, tx)
	} else {
		r0 = ret.Get(0).(specs.InvitationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetRequest, pgx.Tx) error); ok {
		r1 = rf(ctx, getRequest, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfileCompleteStatus provides a mock function with given fields: ctx, profileID, updateReq, tx
func (_m *EmailStorer) UpdateProfileCompleteStatus(ctx context.Context, profileID int, updateReq repository.UpdateRequest, tx pgx.Tx) error {
	ret := _m.Called(ctx, profileID, updateReq, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileCompleteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, repository.UpdateRequest, pgx.Tx) error); ok {
		r0 = rf(ctx, profileID, updateReq, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailStorer creates a new instance of EmailStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailStorer {
	mock := &EmailStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
