// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/profile_builder_backend_go/internal/repository"
)

// ProfileStorer is an autogenerated mock type for the ProfileStorer type
type ProfileStorer struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, values
func (_m *ProfileStorer) CreateEducation(ctx context.Context, values []repository.EducationDao) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.EducationDao) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProfile provides a mock function with given fields: ctx, profileDetail
func (_m *ProfileStorer) CreateProfile(ctx context.Context, profileDetail dto.CreateProfileRequest) error {
	ret := _m.Called(ctx, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) error); ok {
		r0 = rf(ctx, profileDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProject provides a mock function with given fields: ctx, values
func (_m *ProfileStorer) CreateProject(ctx context.Context, values []repository.ProjectDao) error {
	ret := _m.Called(ctx, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.ProjectDao) error); ok {
		r0 = rf(ctx, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProfiles provides a mock function with given fields: ctx
func (_m *ProfileStorer) ListProfiles(ctx context.Context) ([]dto.ListProfiles, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 []dto.ListProfiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.ListProfiles, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.ListProfiles); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListProfiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileStorer creates a new instance of ProfileStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileStorer {
	mock := &ProfileStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
