// Code generated by mockery v2.40.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/profile_builder_backend_go/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateEducation provides a mock function with given fields: ctx, eduDetail
func (_m *Service) CreateEducation(ctx context.Context, eduDetail dto.CreateEducationRequest) error {
	ret := _m.Called(ctx, eduDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateEducationRequest) error); ok {
		r0 = rf(ctx, eduDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProfile provides a mock function with given fields: ctx, profileDetail
func (_m *Service) CreateProfile(ctx context.Context, profileDetail dto.CreateProfileRequest) error {
	ret := _m.Called(ctx, profileDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProfileRequest) error); ok {
		r0 = rf(ctx, profileDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProject provides a mock function with given fields: ctx, projDetail
func (_m *Service) CreateProject(ctx context.Context, projDetail dto.CreateProjectRequest) error {
	ret := _m.Called(ctx, projDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProjectRequest) error); ok {
		r0 = rf(ctx, projDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProfiles provides a mock function with given fields: ctx
func (_m *Service) ListProfiles(ctx context.Context) ([]dto.ListProfiles, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 []dto.ListProfiles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.ListProfiles, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.ListProfiles); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ListProfiles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
