-- DROP TABLE IF EXISTS users;

-- DROP TABLE IF EXISTS profiles;

DROP TABLE IF EXISTS educations;

DROP TABLE IF EXISTS certificates;

DROP TABLE IF EXISTS projects;

DROP TABLE IF EXISTS achievements;

DROP TABLE IF EXISTS experiences;

DROP TABLE IF EXISTS skills;
